server_addr: '172.17.0.1:9991'
port: 9000
debug: Yes
use_ssl: Yes
ssl_cert: 'config/cert.pem'
ssl_key: 'config/key.pem'
timeout: 5  #{timeout in seconds}
modules:
  sqli:
    enabled: Yes
    mode: 1  #{ 1=block }
  xss:
    enabled: Yes
    mode: 0  #{ 0=mitigate|1=block }
  security_headers:
    enabled: Yes
  rate_limiter:
    enabled: Yes
    default_limits: '5000/day;500/hour'  #{'5000/day;500/hour;...'}